services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4173:4173"
    networks:
      - petadoption-net
    depends_on:
      - backend

  backend:
    build:
      context: ./pet-adoption-platform-servers-site
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "5007:5007"
    networks:
      - petadoption-net

networks:
  petadoption-net:
    driver: bridge

volumes:
  mongo-data:
    # Persistent storage for MongoDB
